### ISSUE TITLE
Installing failed after "downloading missing archives"

### ISSUE THREAD

**Issue by ky36789** [TitansBane/Elysium#215] opened 2021-11-13 00:09 UTC

**Comment by ky36789** [comment] 2021-11-13 11:48
854.51 - File hash check (-42) dab8df89c3606cd55f4e65fdc4899238c79a6aeb62c93dd5c31642dbd86531d2
854.54 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
855.64 - Hashed download is incorrect
855.64 - Loading for alternative to U659DN1scQM=
855.75 - No alternative for U659DN1scQM= could be found
855.79 - Hashing Remaining Archives
855.79 - Looking for files to hash
856 - Found 2107 total files, 1564 matching filesize
856.32 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
856.32 - Cannot continue, was unable to download one or more archives
856.32 - File hash check (-42) dab8df89c3606cd55f4e65fdc4899238c79a6aeb62c93dd5c31642dbd86531d2
856.32 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives

**Comment by FunkyBonks** [comment] 2021-11-13 12:24
Is the TUDM mod the only thing missing? Or some other .bsa files that skyrim generates?
Having a similar problem with TUDM,  but also says that' s missing some basic skyrim files.

If it's only TUDM that's missing, there's another issue here that has a dowloand for TUDM, just copy it to the downloaded folder. And if TUDM is the only thing missing, how is your Skyrim installed? Through steam? Does it recognize Skyrim's .bsa files?

If it's also missing skyrim .bsa files, then we're waiting in the dark lol (issue 28)

**Comment by welch3694** [comment] 2021-11-14 19:53
This is a duplicate of https://github.com/TitansBane/Elysium/issues/188 and the link to download a valid .rar is there

**Closed** 2022-02-03 01:18 UTC
